# Generated by Django 4.2 on 2023-07-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='companydata',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='markettime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeid', models.CharField(max_length=255)),
                ('mtime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='oems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oemid', models.CharField(max_length=255)),
                ('oem_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatorid', models.CharField(max_length=255)),
                ('operatorname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='uploaded_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/')),
                ('processed_file', models.FileField(upload_to='downloads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='marketdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketname', models.CharField(max_length=255)),
                ('Specific_Market_Guidline', models.CharField(max_length=255)),
                ('Ciq', models.FileField(null=True, upload_to='marketdata')),
                ('Call_test_info', models.FileField(null=True, upload_to='marketdata')),
                ('Call_test_files', models.FileField(null=True, upload_to='marketdata')),
                ('Site_access', models.FileField(null=True, upload_to='marketdata')),
                ('Guidelines', models.FileField(null=True, upload_to='marketdata')),
                ('additional_Guidelines', models.FileField(null=True, upload_to='marketdata')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientname')),
                ('oemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.oems')),
                ('operatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
                ('timeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.markettime')),
            ],
        ),
        migrations.CreateModel(
            name='infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('password', models.CharField(max_length=255)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companydata')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='activitylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(choices=[('Nokia', 'Nokia'), ('Ericsson', 'Ericsson')], max_length=255)),
                ('Ticket_Number', models.IntegerField()),
                ('fa_location', models.TextField()),
                ('site_ids', models.TextField()),
                ('Added_Date', models.TextField()),
                ('County', models.TextField()),
                ('Activity', models.TextField(null=True)),
                ('Ix_Date', models.TextField()),
                ('G_IX_date', models.IntegerField()),
                ('Ticket_Status', models.TextField()),
                ('lite_site_id', models.TextField()),
                ('three_g_site_id', models.TextField()),
                ('Field_Installation', models.TextField()),
                ('Alarm', models.TextField()),
                ('Field_Integration', models.TextField()),
                ('remote_Integration', models.TextField()),
                ('five_g_site_id', models.TextField()),
                ('site_name', models.TextField()),
                ('market', models.TextField()),
                ('address', models.TextField()),
                ('zip_code', models.TextField()),
                ('Added_By', models.TextField()),
                ('IX_Status', models.TextField()),
                ('CX_Status', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('mon_hours', models.TextField()),
                ('tue_hours', models.TextField()),
                ('wed_hours', models.TextField()),
                ('thu_hours', models.TextField()),
                ('fri_hours', models.TextField()),
                ('sat_hours', models.TextField()),
                ('sun_hours', models.TextField()),
                ('key_comments', models.TextField()),
                ('notice_needed', models.TextField()),
                ('notice_comments', models.TextField()),
                ('num_of_carrier', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('pace', models.TextField()),
                ('ptn', models.TextField()),
                ('sow_type', models.TextField(choices=[('TroubleShooting ', 'TroubleShooting '), ('Maintainance', 'Maintainance '), ('Equipment change  ', 'Equipment change  ')])),
                ('wo_cr_id', models.TextField()),
                ('sow', models.TextField()),
                ('ix_schedule_date', models.DateField()),
                ('nest', models.TextField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('mop_start_time', models.TimeField()),
                ('mop_end_time', models.TimeField()),
                ('assign_fe', models.CharField(choices=[('Jacob Adams', 'Jacob Adams'), ('Neiol', 'Neiol'), ('Bhorjn', 'Bhorjn')], max_length=255)),
                ('ix_date_comment', models.TextField()),
                ('equipment_pickup', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('five_g_ix_standalone', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('five_g_ix_schedule_date', models.DateField()),
                ('call_test_date', models.DateField()),
                ('market_state', models.TextField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')])),
                ('crew_dispatch_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientname')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
        ),
    ]
